/**
 * In this example, 100 articles have been created. To fetch them, run:

 curl http://localhost:4000/articles

 * Note that only 10 have been returned. A default limit of 10 has been set.
 *
 * To set another limit, use:

 curl http://localhost:4000/articles?limit=20

 * The default offset is 0. To specify it (note the double quotes):

 curl "http://localhost:4000/articles?limit=20&offset=30"

  * To see the `WebLinks` generated by this example, see the `Link` header after running:

  curl -v "http://localhost:4000/articles?limit=20&offset=30"

*/

const app = require('express')();
require('./mongoose.js');
const bodyParser = require('body-parser')
const models = require('./models/index.js');
const routes = require('./routes/index.js');

app.use(bodyParser.json()) // for parsing application/json
app.use((req, res, next) => {
    req.context = {models,};
    next();
});

app.use('/articles', routes.article);
app.listen(4000, () => console.log('Running a REST server at http://localhost:4000/'));
